---
title: "Assignment 2: Scrutinizing data analyses"
output:
  html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Suggestions for papers

We suggest using a range of papers for this assignment, unless the class is very small.

-   We choose papers across a range of biological disciplines, so students can choose a paper close to their research field

-   We require students to sign up for a paper using the Learning Management System. This allows us the opportunity to cap the number of assignments on each paper, reducing opportunities for collusion.

    -   We've not found collusion to be a problem, based on comparison of answers.

    -   We use roughly 7-9 students per paper, but that's a pretty arbitrary choice.

-   You need to keep an eye out for papers with interesting flaws, and this task needs to go year-round. It's hard to find papers quickly.

    -   Asking colleagues to look for examples

-   It can be a challenge to find issues that are not too obvious or too complicated

-   The two questions about what the authors state they found and what the student thinks they found, after scrutinizing the analysis, is intended to make sure that students consider whether any of the issues they identify are likely to change the conclusions materially

-   We have found that a paper can be used a couple of times without any issues. No formal analysis here, but we have gone and checked previous year's submitted assignments when looking at the current year.

## Preparing for the assignment

In past years, we've run this assignment without any specific preparation in tutorials/pracs, but in the past couple of years we noticed students struggling a little, so we added an in-class exercise that was essentially a practice run.

We:

-   used a single paper,

-   split the class into groups of 4-6

-   asked them to work through the questions from the assignment

    -   We allowed 30-45 minutes for this stage, but it could be broken up into a couple of shorter sessions

-   had a report-back session to workshop the answers to questions

## Notes for this assignment

-   Remind students they're not expected to do any additional reading

-   The table, with its allotted marks, is the rubric for the assignment. A table with cells to be filled keeps the answers on point.

-   Depending on the LMS, we have provided a Word version of the table, which students fill and upload, and we've also used Gradescope to have answers filled in directly and saved.

    -   It may also be possible to have students complete the assignment in R, using *learnr.* We're not qute there yet.

## Feedback

We've typically taught as an intensive subject between semesters. In this model, students have been happy with written feedback, and face-to-face small group sessions aren't as valuable for this assignment as for Assignment 1. It may also be that with a new semester starting, plus the exam, students are focused elsewhere.

## Submission table

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| #### What (biological) question(s) were the data designed to answer? (2 marks)                                                                                                                  |
+=================================================================================================================================================================================================+
| #### What kind of statistical model(s) were fitted to the data? (2 marks)                                                                                                                       |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| #### Describe your preliminary conclusion, based on what the authors said about their results (2 marks)                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| #### Outline the assumptions associated with the statistical model(s) used (2 marks)                                                                                                            |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| #### Did the authors provide you with enough information to determine whether the data analysis is appropriate? If not, w hat additional information would you like to see presented? (4 marks) |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| #### What changes would you make to the data analysis? (4 marks)                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| #### What would you conclude after your assessment of the data analysis? (4 marks)                                                                                                              |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
